//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LURecCenter.DAL.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedInUser
    {
        public long LoginID { get; set; }
        public Nullable<int> LoggedINUserID { get; set; }
        public string LoggedInUserName { get; set; }
        public Nullable<System.DateTime> LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOut { get; set; }
        public Nullable<bool> ISActive { get; set; }
    }
}
