//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LURecCenter.DAL.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIssuedEquipment
    {
        public int IssueID { get; set; }
        public int EquipmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> IssueOn { get; set; }
        public Nullable<System.DateTime> ReturnOn { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public string IssueComments { get; set; }
        public string RetComments { get; set; }
        public string Attribute1 { get; set; }
    
        public virtual tblEquipment tblEquipment { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
