//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LURecCenter.DAL.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLoggedInUser
    {
        public int SessionId { get; set; }
        public Nullable<int> Userid { get; set; }
        public string UserName { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.TimeSpan> LoggedOuttime { get; set; }
        public Nullable<System.DateTime> LoggedOutdate { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
