//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LURecCenter.DAL.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblShift
    {
        public long ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string ShiftComment { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<bool> Avilable { get; set; }
        public Nullable<int> PickedByUser { get; set; }
        public Nullable<System.DateTime> PickedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Shiftto { get; set; }
        public string Shiftfrom { get; set; }
    }
}
