//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LURecCenter.DAL.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWritesUp
    {
        public int WritesupID { get; set; }
        public string WritesUpText { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TOUser { get; set; }
    }
}
