<%@ Page Title="About Us" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="LURecCenterWeb.UI.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <br /> <img alt="" src="file:///C:/Users/ojusa_000/Downloads/RecCenter%20Project/Images/allco-test-1.jpg" style="width: 870px; height: 350px" /></h2>
    
    <br /> <h2><%: Title %>
    <h3>    You may be interested to know that ..</h3>
    <p><span style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; ">Rec Sports programs include Fitness and Wellness, Intramural Sports, Sport Clubs, Outdoor Pursuits, Aquatics, and Informal Recreation. Our facilities include the Sheila Umphrey Recreational Sports Center, the Indoor Pool, and the Golf Driving Range.</span><br style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
        <span style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; ">There&#39;s always something happening in Rec Sports! We encourage you to join in on the fun!</span><br style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; " />
        </p>
    <p><span style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; ">Looking for more information? Please feel free to contact us by phone at (409) 880-2306, or e-mail us at&nbsp;</span><a href="mailto:RecSports@Lamar.edu" style="color: rgb(0, 0, 0); font-weight: 500; text-decoration: none; font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">RecSports@Lamar.edu</a><br style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" />
        </p>
    <p><span style="color: rgb(85, 85, 85); font-family: Roboto, arial, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0.42px; line-height: 19.88px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; ">If you would like to schedule a group tour of the Sheila Umphrey Recreational Sports Center, contact Balinda Cooper, Executive Assistant at (409) 880-7585.</span></p>
</asp:Content>
